site_name: NetDaemon - Application daemon written in .NET core.
theme: 'material' #readthedocs
# google_analytics:
#   - UA-133997912-1
#   - auto
repo_url: https://github.com/helto4real/netdaemon/
site_dir: site
site_author: 'Tomas Hellström, @helto4real'
dev_addr: 127.0.0.1:8001
markdown_extensions:
    - fenced_code
    - codehilite
# nav:
#     - Home: index.md